import sqlite3

conn = sqlite3.connect(r'd:/IA/Softwares/IA Poker/tournaments.db')
cur = conn.cursor()
cur.execute('PRAGMA foreign_keys = OFF')
cur.execute('BEGIN TRANSACTION')
cur.execute('CREATE TABLE IF NOT EXISTS countrycity_new (id INTEGER PRIMARY KEY, name TEXT UNIQUE NOT NULL)')
cur.execute('INSERT OR IGNORE INTO countrycity_new (id, name) SELECT id, name FROM countrycity')
cur.execute('CREATE TABLE IF NOT EXISTS players_new (id INTEGER PRIMARY KEY, pseudo TEXT NOT NULL UNIQUE, type TEXT, id_countrycity INTEGER, FOREIGN KEY(id_countrycity) REFERENCES countrycity(id))')
cur.execute('INSERT OR REPLACE INTO players_new (id, pseudo, type, id_countrycity) SELECT id, pseudo, type, id_countrycity FROM players')
cur.execute('DROP TABLE players')
cur.execute('DROP TABLE countrycity')
cur.execute('ALTER TABLE countrycity_new RENAME TO countrycity')
cur.execute('ALTER TABLE players_new RENAME TO players')
cur.execute('PRAGMA foreign_keys = ON')
conn.commit()
conn.close()
print('migrated')
